"""empty message

Revision ID: 47d6df98c285
Revises: 32f739e8e59e
Create Date: 2023-01-04 02:23:51.353922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6df98c285'
down_revision = '32f739e8e59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('Diameter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fav__people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_name', sa.String(length=120), nullable=True),
    sa.Column('user_fav', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['people_name'], ['people.name'], ),
    sa.ForeignKeyConstraint(['user_fav'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planets_name', sa.String(length=120), nullable=True),
    sa.Column('user_fav', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['planets_name'], ['planets.name'], ),
    sa.ForeignKeyConstraint(['user_fav'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__planets')
    op.drop_table('fav__people')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
